TrajectoryPlannerROS:
  max_vel_x: 0.8
  min_vel_x: 0.01
  max_vel_theta: 0.5
  min_in_place_vel_theta: 0.3

  acc_lim_theta: 1.0
  acc_lim_x: 1.0
  acc_lim_y: 0.0

  holonomic_robot: false

  meter_scoring : true

  controller_frequency: 10.0

