controller_frequency: 20.0
controller_patience: 15.0 

planner_frequency: 1.0
planner_patience: 5.0

shutdown_costmaps: false
oscillation_timeout: 0.0
oscillation_distance: 0.5

recovery_behavior_enabled: true
clearing_rotation_allowed: false